# Btop Cyberpunk theme (https://github.com/ImanolFotia/cyberpunk-btop-theme)
# By: Imanol Fotia

# Main bg
theme[main_bg]="#060a0f"

# Main text color
theme[main_fg]="#7d2928"

# Title color for boxes
theme[title]="#2cb8bd"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#744d1e"

# Background color of selected item in processes box
theme[selected_bg]="#7b2526"

# Foreground color of selected item in processes box
theme[selected_fg]="#2cb8bd"

# Color of inactive/disabled text
theme[inactive_fg]="#3c5056"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#1bd576"

# Cpu box outline color
theme[cpu_box]="#b63c38"

# Memory/disks box outline color
theme[mem_box]="#b63c38"

# Net up/down box outline color
theme[net_box]="#b63c38"

# Processes box outline color
theme[proc_box]="#b63c38"

# Box divider line and small boxes line color
theme[div_line]="#b63c38"

# Temperature graph colors
theme[temp_start]="#01477a"
theme[temp_mid]="#8c5e94"
theme[temp_end]="#f6c209"

# Power graph colors
theme[power_start]="#01477a"
theme[power_mid]="#8c5e94"
theme[power_end]="#f6c209"

# CPU graph colors
theme[cpu_start]="#01477a"
theme[cpu_mid]="#8c5e94"
theme[cpu_end]="#f6c209"

# Mem/Disk free meter
theme[free_start]="#01477a"
theme[free_mid]="#8c5e94"
theme[free_end]="#F6c209"

# Mem/Disk cached meter
theme[cached_start]="#01477a"
theme[cached_mid]="#8c5e94"
theme[cached_end]="#F6c209"

# Mem/Disk available meter
theme[available_start]="#1ad977"
theme[available_mid]="#957FBB"
theme[available_end]="#9CABCA"

# Mem/Disk used meter
theme[used_start]="#1ad977"
theme[used_mid]="#7E9CDB"
theme[used_end]="#7FB4CA"

# Download graph colors
theme[download_start]="#1ad977"
theme[download_mid]="#938AA9"
theme[download_end]="#957FBB"

# Upload graph colors
theme[upload_start]="#DCA561"
theme[upload_mid]="#E6C384"
theme[upload_end]="#E82424"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#01477a"
theme[process_mid]="#8c5e94"
theme[process_end]="#f6c209"

